name: Deploy Next.js Image to AWS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  s3ls:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: 'arn:aws:iam::637423353319:role/oidc-github-kanta-portfolio-push-ecr-role'

      - run: aws s3 ls s3


